spring:
  data:
    mongodb:
      host: localhost  # MongoDB host (use the container name if using Docker)
      port: 27017  # MongoDB port
      database: customer_service  # Name of the MongoDB database
      username: root  # Username for authentication
      password: mypassword  # Password for authentication
      authentication-database: admin  # Authentication database (default is "admin")
server:
  port: 8090