spring:
  datasource:
    url: jdbc:postgresql://localhost:5430/order_db
    username: root
    password: mypassword
    driver-class-name: org.postgresql.Driver

  kafka:
    bootstrap-servers: localhost:9092  # Kafka broker address
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer  # Serializer for keys
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer  # Serializer for values
      properties:
        spring.json.type.mapping: orderConfirmation:com.ganeshgc.orderservice.kafka.OrderConfirmation

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  application:
    config:
      customer-url: http://localhost:8222/api/v1/customers
      product-url: http://localhost:8222/api/v1/products
      payment-url: http://localhost:8222/api/v1/payments

server:
  port: 8070
