spring:
  datasource:
    url: jdbc:postgresql://localhost:5430/payment_db
    username: root
    password: mypassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    bootstrap-servers: localhost:9092  # Kafka broker address
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer  # Serializer for keys
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer  # Serializer for values
      properties:
        spring.json.type.mapping: paymentConfirmation:com.ganeshgc.paymentservice.notification.PaymentNotificationRequest