server:
  port: 8888  # Port on which Config Server will run


spring:
  profiles:
    active: native  # Run Config Server in native mode
  application:
    name: config-server  # The name of your Config Server application
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configurations  # Where to look for config files

